-- Run this in the Supabase SQL Editor

create table if not exists users (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  phone text not null,
  station text not null
);

-- Optional: Enable Row Level Security (RLS)
alter table users enable row level security;

-- Policy to allow anyone to insert (since we have a public signup form)
create policy "Enable insert for everyone" on users for insert with check (true);

-- Policy to allow the service_role (backend) to read everything
-- (Service role bypasses RLS by default, but good to know)
